dependencies {
  implementation project(':modelers-api')

  // openflexo dep
  implementation flexoFoundation()

  // Technology adapters used by the modelers of modelers-rc
  implementation emfConnector()
  implementation diagramConnector()
  implementation ginaConnector()
  implementation owlConnector()

  // testing dep
  implementation testUtils()
  implementation flexoFoundationTest()

  // Resource center under test
  testRuntimeOnly project(':modelers-rc')
}
